services:

  pg:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata:
