services:

  pg:
    image: postgres:17.5
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U seaweed -h postgres -p 5434" ]
      interval: 5s
      timeout: 5s
      retries: 5
  s3mock:
    image: adobe/s3mock:latest
    environment:
      - initialBuckets=images
      - debug=true
      - retainFilesOnExit=true
      - root=containers3root
    ports:
      - 9090:9090
      - 9191:9191
    volumes:
      - ./locals3root:/containers3root
volumes:
  pgdata:


