defmodule Smalltalk.Repo.Migrations.AddUniqueUserConstraintToTalker do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:talkers, [:user_id],
             name: "talkers_unique_user_index",
             prefix: "conversations"
           )
  end

  def down do
    drop_if_exists unique_index(:talkers, [:user_id],
                     name: "talkers_unique_user_index",
                     prefix: "conversations"
                   )
  end
end
