defmodule Smalltalk.Repo.Migrations.AddFriendsAndRequests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS friendships")

    create table(:requests, primary_key: false, prefix: "friendships") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :status, :text, default: "pending"
      add :requester_id, :uuid
      add :requested_id, :uuid
    end

    execute("CREATE SCHEMA IF NOT EXISTS friendships")

    create table(:friends, primary_key: false, prefix: "friendships") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:requests, prefix: "friendships") do
      modify :requester_id,
             references(:friends, column: :id, name: "requests_requester_id_fkey", type: :uuid)

      modify :requested_id,
             references(:friends, column: :id, name: "requests_requested_id_fkey", type: :uuid)
    end

    create unique_index(:requests, [:requester_id, :requested_id],
             name: "requests_unique_pair_index",
             prefix: "friendships"
           )

    alter table(:friends, prefix: "friendships") do
      add :user_id,
          references(:users,
            column: :id,
            name: "friends_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:friends, "friends_user_id_fkey", prefix: "friendships")

    alter table(:friends, prefix: "friendships") do
      remove :user_id
    end

    drop_if_exists unique_index(:requests, [:requester_id, :requested_id],
                     name: "requests_unique_pair_index",
                     prefix: "friendships"
                   )

    drop constraint(:requests, "requests_requester_id_fkey", prefix: "friendships")

    drop constraint(:requests, "requests_requested_id_fkey", prefix: "friendships")

    alter table(:requests, prefix: "friendships") do
      modify :requested_id, :uuid
      modify :requester_id, :uuid
    end

    drop table(:friends, prefix: "friendships")

    drop table(:requests, prefix: "friendships")
  end
end
