defmodule Smalltalk.Repo.Migrations.AddLastActiveAttributeToConversation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:participants, prefix: "conversations") do
      add :last_active, :utc_datetime
    end
  end

  def down do
    alter table(:participants, prefix: "conversations") do
      remove :last_active
    end
  end
end
