defmodule Smalltalk.Repo.Migrations.CreateUploadImageResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :s3_root_path, :text, null: false
      add :type, :text
      add :extension, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "images_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:images, "images_user_id_fkey")

    drop table(:images)
  end
end
