defmodule Smalltalk.Repo.Migrations.AddSchemaToProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS conversations")

    create table(:profiles, primary_key: false, prefix: "conversations") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :first_name, :text
      add :last_name, :text
      add :nickname, :text
      add :image_src, :text
      add :age, :bigint
      add :location, :text
      add :relationship_status, :text
      add :personality_traits, :text
      add :hobbies, :text
      add :profession, :text
      add :education, :text

      add :talker_id,
          references(:talkers,
            column: :id,
            name: "profiles_talker_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )
    end

    create unique_index(:profiles, [:talker_id],
             name: "profiles_unique_talker_index",
             prefix: "conversations"
           )
  end

  def down do
    drop_if_exists unique_index(:profiles, [:talker_id],
                     name: "profiles_unique_talker_index",
                     prefix: "conversations"
                   )

    drop constraint(:profiles, "profiles_talker_id_fkey", prefix: "conversations")

    drop table(:profiles, prefix: "conversations")
  end
end
