defmodule Smalltalk.Repo.Migrations.AddLeftAtFieldToConversatinParticipants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:participants, prefix: "conversations") do
      add :left_at, :utc_datetime
    end
  end

  def down do
    alter table(:participants, prefix: "conversations") do
      remove :left_at
    end
  end
end
