defmodule Smalltalk.Repo.Migrations.AddUniqueTalkerConversationConstraintToReceipts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:read_receipts, [:talker_id, :conversation_id],
             name: "read_receipts_unique_talker_conversation_index",
             prefix: "conversations"
           )
  end

  def down do
    drop_if_exists unique_index(:read_receipts, [:talker_id, :conversation_id],
                     name: "read_receipts_unique_talker_conversation_index",
                     prefix: "conversations"
                   )
  end
end
