defmodule Smalltalk.Repo.Migrations.AddImageIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:images, [:s3_root_path, :type, :extension],
             name: "images_root_path_type_extension_index"
           )
  end

  def down do
    drop_if_exists unique_index(:images, [:s3_root_path, :type, :extension],
                     name: "images_root_path_type_extension_index"
                   )
  end
end
