defmodule Smalltalk.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:participants, prefix: "conversations") do
      add :approved?, :boolean

      add :approved_by_id,
          references(:admins,
            column: :id,
            name: "participants_approved_by_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )
    end
  end

  def down do
    drop constraint(:participants, "participants_approved_by_id_fkey", prefix: "conversations")

    alter table(:participants, prefix: "conversations") do
      remove :approved_by_id
      remove :approved?
    end
  end
end
