defmodule Smalltalk.Repo.Migrations.UndoProfileConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:profiles, prefix: "conversations") do
      modify :education, :text, null: true
      modify :profession, :text, null: true
      modify :hobbies, :text, null: true
      modify :relationship_status, :text, null: true
      modify :location, :text, null: true
      modify :age, :bigint, null: true
      modify :image_src, :text, null: true
    end
  end

  def down do
    alter table(:profiles, prefix: "conversations") do
      modify :image_src, :text, null: false
      modify :age, :bigint, null: false
      modify :location, :text, null: false
      modify :relationship_status, :text, null: false
      modify :hobbies, :text, null: false
      modify :profession, :text, null: false
      modify :education, :text, null: false
    end
  end
end
