defmodule Smalltalk.Repo.Migrations.AddConversationResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS conversations")

    create table(:talkers, primary_key: false, prefix: "conversations") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "talkers_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    execute("CREATE SCHEMA IF NOT EXISTS conversations")

    create table(:read_receipts, primary_key: false, prefix: "conversations") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :talker_id,
          references(:talkers,
            column: :id,
            name: "read_receipts_talker_id_fkey",
            type: :uuid,
            prefix: "conversations"
          ),
          null: false

      add :conversation_id, :uuid, null: false
      add :most_recent_message_id, :uuid
    end

    create table(:profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :first_name, :text
      add :last_name, :text
      add :nickname, :text

      add :talker_id,
          references(:talkers,
            column: :id,
            name: "profiles_talker_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )
    end

    execute("CREATE SCHEMA IF NOT EXISTS conversations")

    create table(:messages, primary_key: false, prefix: "conversations") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :content, :text
      add :conversation_id, :uuid
      add :talker_id, :uuid
    end

    execute("CREATE SCHEMA IF NOT EXISTS conversations")

    create table(:conversations, primary_key: false, prefix: "conversations") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:read_receipts, prefix: "conversations") do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "read_receipts_conversation_id_fkey",
               type: :uuid
             )

      modify :most_recent_message_id,
             references(:messages,
               column: :id,
               name: "read_receipts_most_recent_message_id_fkey",
               type: :uuid
             )
    end

    alter table(:messages, prefix: "conversations") do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid
             )

      modify :talker_id,
             references(:talkers, column: :id, name: "messages_talker_id_fkey", type: :uuid)
    end

    alter table(:conversations, prefix: "conversations") do
      add :short_name, :text
      add :description, :text
    end
  end

  def down do
    alter table(:conversations, prefix: "conversations") do
      remove :description
      remove :short_name
    end

    drop constraint(:messages, "messages_conversation_id_fkey", prefix: "conversations")

    drop constraint(:messages, "messages_talker_id_fkey", prefix: "conversations")

    alter table(:messages, prefix: "conversations") do
      modify :talker_id, :uuid
      modify :conversation_id, :uuid
    end

    drop constraint(:read_receipts, "read_receipts_conversation_id_fkey", prefix: "conversations")

    drop constraint(:read_receipts, "read_receipts_most_recent_message_id_fkey",
           prefix: "conversations"
         )

    alter table(:read_receipts, prefix: "conversations") do
      modify :most_recent_message_id, :uuid
      modify :conversation_id, :uuid
    end

    drop table(:conversations, prefix: "conversations")

    drop table(:messages, prefix: "conversations")

    drop constraint(:profiles, "profiles_talker_id_fkey")

    drop table(:profiles)

    drop constraint(:read_receipts, "read_receipts_talker_id_fkey", prefix: "conversations")

    drop table(:read_receipts, prefix: "conversations")

    drop constraint(:talkers, "talkers_user_id_fkey", prefix: "conversations")

    drop table(:talkers, prefix: "conversations")
  end
end
