defmodule Smalltalk.Repo.Migrations.AddUserIdIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:friends, [:user_id],
             name: "friends_unique_user_id_index",
             prefix: "friendships"
           )
  end

  def down do
    drop_if_exists unique_index(:friends, [:user_id],
                     name: "friends_unique_user_id_index",
                     prefix: "friendships"
                   )
  end
end
