defmodule Smalltalk.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations, prefix: "conversations") do
      add :type, :text, default: "public"
    end
  end

  def down do
    alter table(:conversations, prefix: "conversations") do
      remove :type
    end
  end
end
