defmodule Smalltalk.Repo.Migrations.AddConversationParticipants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS conversations")

    create table(:participants, primary_key: false, prefix: "conversations") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "participants_conversation_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )

      add :talker_id,
          references(:talkers,
            column: :id,
            name: "participants_talker_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )
    end

    create unique_index(:participants, [:conversation_id, :talker_id],
             name: "participants_unique_talker_index",
             prefix: "conversations"
           )
  end

  def down do
    drop_if_exists unique_index(:participants, [:conversation_id, :talker_id],
                     name: "participants_unique_talker_index",
                     prefix: "conversations"
                   )

    drop constraint(:participants, "participants_conversation_id_fkey", prefix: "conversations")

    drop constraint(:participants, "participants_talker_id_fkey", prefix: "conversations")

    drop table(:participants, prefix: "conversations")
  end
end
