defmodule Smalltalk.Repo.Migrations.AddUniqueTalkerConstraintToProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:profiles, [:talker_id], name: "profiles_unique_talker_index")
  end

  def down do
    drop_if_exists unique_index(:profiles, [:talker_id], name: "profiles_unique_talker_index")
  end
end
