defmodule Smalltalk.Repo.Migrations.DropImgFromProfiels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:profiles, prefix: "conversations") do
      remove :image_src
    end
  end

  def down do
    alter table(:profiles, prefix: "conversations") do
      add :image_src, :text
    end
  end
end
