defmodule Smalltalk.Repo.Migrations.ChangeCurrentProfilePicRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:talkers, prefix: "conversations") do
      add :current_profile_pic_id,
          references(:profile_pics,
            column: :id,
            name: "talkers_current_profile_pic_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )
    end
  end

  def down do
    drop constraint(:talkers, "talkers_current_profile_pic_id_fkey", prefix: "conversations")

    alter table(:talkers, prefix: "conversations") do
      remove :current_profile_pic_id
    end
  end
end
