defmodule Smalltalk.Repo.Migrations.DropImageFormatColumn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:images, prefix: "uploads") do
      remove :format
      modify :extension, :text, default: "webp"
    end
  end

  def down do
    alter table(:images, prefix: "uploads") do
      modify :extension, :text, default: nil
      add :format, :text, default: "webp"
    end
  end
end
