defmodule Smalltalk.Repo.Migrations.AddUploadsSchemaToImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS uploads")

    create table(:images, primary_key: false, prefix: "uploads") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :s3_root_path, :text, null: false
      add :type, :text
      add :extension, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "images_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:images, [:s3_root_path, :type, :extension],
             name: "images_root_path_type_extension_index",
             prefix: "uploads"
           )
  end

  def down do
    drop_if_exists unique_index(:images, [:s3_root_path, :type, :extension],
                     name: "images_root_path_type_extension_index",
                     prefix: "uploads"
                   )

    drop constraint(:images, "images_user_id_fkey", prefix: "uploads")

    drop table(:images, prefix: "uploads")
  end
end
