defmodule Smalltalk.Repo.Migrations.AddSchemaToProfilePics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS conversations")

    create table(:profile_pics, primary_key: false, prefix: "conversations") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :original_src, :text, null: false

      add :talker_id,
          references(:talkers,
            column: :id,
            name: "profile_pics_talker_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )
    end
  end

  def down do
    drop constraint(:profile_pics, "profile_pics_talker_id_fkey", prefix: "conversations")

    drop table(:profile_pics, prefix: "conversations")
  end
end
