defmodule Smalltalk.Repo.Migrations.AddConversationAdminTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:participants, prefix: "conversations") do
      add :blocked?, :boolean, default: false
    end

    alter table(:messages, prefix: "conversations") do
      modify :content, :text, null: false
    end

    execute("CREATE SCHEMA IF NOT EXISTS conversations")

    create table(:admins, primary_key: false, prefix: "conversations") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "admins_conversation_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )

      add :talker_id,
          references(:talkers,
            column: :id,
            name: "admins_talker_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )
    end
  end

  def down do
    drop constraint(:admins, "admins_conversation_id_fkey", prefix: "conversations")

    drop constraint(:admins, "admins_talker_id_fkey", prefix: "conversations")

    drop table(:admins, prefix: "conversations")

    alter table(:messages, prefix: "conversations") do
      modify :content, :text, null: true
    end

    alter table(:participants, prefix: "conversations") do
      remove :blocked?
    end
  end
end
