defmodule Smalltalk.Repo.Migrations.AddAdditionalFriendActions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS conversations")

    create table(:friendship_requests, primary_key: false, prefix: "conversations") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :status, :text, default: "pending"
      add :accepted_at, :utc_datetime
      add :rejected_at, :utc_datetime

      add :requester_id,
          references(:talkers,
            column: :id,
            name: "friendship_requests_requester_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )

      add :requested_id,
          references(:talkers,
            column: :id,
            name: "friendship_requests_requested_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )

      add :unfriended_by_id,
          references(:talkers,
            column: :id,
            name: "friendship_requests_unfriended_by_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )
    end

    create unique_index(:friendship_requests, [:requester_id, :requested_id],
             name: "friendship_requests_unique_pair_index",
             prefix: "conversations"
           )
  end

  def down do
    drop_if_exists unique_index(:friendship_requests, [:requester_id, :requested_id],
                     name: "friendship_requests_unique_pair_index",
                     prefix: "conversations"
                   )

    drop constraint(:friendship_requests, "friendship_requests_requester_id_fkey",
           prefix: "conversations"
         )

    drop constraint(:friendship_requests, "friendship_requests_requested_id_fkey",
           prefix: "conversations"
         )

    drop constraint(:friendship_requests, "friendship_requests_unfriended_by_id_fkey",
           prefix: "conversations"
         )

    drop table(:friendship_requests, prefix: "conversations")
  end
end
