defmodule Smalltalk.Repo.Migrations.AddImageFormat do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:participants, prefix: "conversations") do
      add :approved?, :boolean

      add :approved_by_id,
          references(:admins,
            column: :id,
            name: "participants_approved_by_id_fkey",
            type: :uuid,
            prefix: "conversations"
          )
    end

    alter table(:images, prefix: "uploads") do
      add :format, :text, default: "webp"
    end

    alter table(:conversations, prefix: "conversations") do
      add :type, :text, default: "public"
    end
  end

  def down do
    alter table(:conversations, prefix: "conversations") do
      remove :type
    end

    alter table(:images, prefix: "uploads") do
      remove :format
    end

    drop constraint(:participants, "participants_approved_by_id_fkey", prefix: "conversations")

    alter table(:participants, prefix: "conversations") do
      remove :approved_by_id
      remove :approved?
    end
  end
end
