defmodule Smalltalk.Repo.Migrations.AddUnfriendedAtField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:friendship_requests, prefix: "conversations") do
      add :unfriended_at, :utc_datetime
    end
  end

  def down do
    alter table(:friendship_requests, prefix: "conversations") do
      remove :unfriended_at
    end
  end
end
