defmodule Smalltalk.Repo.Migrations.AddMoreProfileDetails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:profiles) do
      add :image_src, :text
      add :age, :bigint
      add :location, :text
      add :relationship_status, :text
      add :personality_traits, :text
      add :hobbies, :text
      add :profession, :text
      add :education, :text
    end
  end

  def down do
    alter table(:profiles) do
      remove :education
      remove :profession
      remove :hobbies
      remove :personality_traits
      remove :relationship_status
      remove :location
      remove :age
      remove :image_src
    end
  end
end
